import mongoose from "mongoose";

const StudentDataSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'user', required: true },
  dateOfRecord: {type: Date,required: true},
  wakeUpTime: {hour: Number,minute: Number},
  wakingUp: {type: Number,min: 0,max: 10, required: true},
  firstGoOut: {type: Number, min: 0, max: 10, required: true},
  firstScreenOn: {type: Number, min: 0, max: 10, required: true},
  breakfast: { type: Number, min: 0, max: 10, required: true},
  schooling: { type: String, enum: ['Yes', 'No'],required: true},
  classActivity: { type: Number, min: 0, max: 10, required: true},
  outdoorActivity: { type: Number, min: 0, max: 10, required: true},
  therapyAtSchool: { type: String, enum: ['Yes', 'No']},
  therapyType: { type: String, enum: ['OT', 'PT', 'SLT'] },
  lunch: { type: Number, min: 0, max: 10, required: true},
  eveningSnacks: { type: Number, min: 0, max: 10, required: true},
  dinner: { type: Number, min: 0, max: 10, required: true},
  goingToSleep: { type: Number, min: 0, max: 10, required: true},
  goToBedAt: { hour: Number, minute: Number},
  sleepAt: { hour: Number, minute: Number},
  gettingSleepTime: { type: Number, min: 0, max: 10, required: true},
  outgoingTendency: { type: Number,  min: 0, max: 10, required: true}, 
  outgoingCount: { type: Number, min: 0, max: 10, required: true},
  screenTime: { type: Number, min: 0, max: 10, required: true},
  junkFood: { type: Number, min: 0,  max: 10, required: true},
  makingNoise: { type: Number, min: 0, max: 10,required: true},
  walking: { type: Number, min: 0, max: 10, required: true},
  showingAnger: { type: Number, min: 0, max: 10 , required: true},
  glassCrashTendency: { type: Number, min: 0, max: 10, required: true},
  pushingTendency: { type: Number, min: 0, max: 10, required: true},
  itemThrowTendency: { type: Number, min: 0, max: 10 , required: true},
  foodWaterThrowTendency: { type: Number, min: 0, max: 10, required: true},
  hitWithHand: { type: Number, min: 0, max: 10, required: true},
  hitWithHead: { type: Number, min: 0, max: 10, required: true },
  cooperateAtSchool: { type: Number, min: 0, max: 10, required: true },
  cooperateAtHome: { type: Number, min: 0, max: 10, required: true },
  cuttingNails: { type: Number, min: 0, max: 10, required: true },
  hairDressing: { type: Number, min: 0, max: 10, required: true },
  bedwetting: { type: Number, min: 0, max: 10, required: true },
  regularMedication: { type: String, enum: ['Yes', 'No'] },
  otherSickness: { type: String, enum: ['Yes', 'No'] },
  nameOfSickness: { type: String, required: true, trim: true },
  medOtherSickness: { type: String, enum: ['Yes', 'No'] },
  listOfMedicine: { type: String, required: true, trim: true},
  masturbation: { type: Number, min: 0, max: 10, required: true },
  toilet: { type: Number, min: 0, max: 10, required: true },
  overnightSleeping: { type: Number, min: 0, max: 10, required: true},
  specialActivity: { type: String, trim: true},
  // prescriptionReports: { type: String, required: true, trim: true},
  createdAt: { type: Date, default: Date.now }
});

const DataModel = mongoose.model("StudentData", StudentDataSchema);
export default DataModel ;
